### ISSUE TITLE
Custom endpoints for GDPR

### ISSUE THREAD

**Issue by frixaco** [birchill/bugsnag-zero#100]
Hi!

Are there any plans for adding custom endpoints? or maybe some workarounds?

We've been using `bugsnag-js` till now and were forced to use custom endpoints due to GDPR (we don't send data directly to Bugsnag and use our server as a proxy of sort, strip any personal data out of the request and forward it to Bugsnag). Recently, we started working on reducing our app's bundle size and found out `bugsnag-js` is the second after `react-dom` in terms of bundle size.

Thank you for your work on this library. It'd be really cool if we could replace bugsnag-js with `bugsnag-zero`.

**Comment by birtles** [comment]
Thanks for your interest!

Yes, I started this project because I found `bugnsag-js` was the biggest dependency in my project.

Regarding custom endpoints, I wonder if setting a custom delivery mechanism would work. You can see an example in [the docs for Node.js](https://github.com/birchill/bugsnag-zero#usage-with-nodejs).

Specifically, when we use this on Node.js (AWS Lambda) we plug in our own delivery mechanism to have the messages sent to an SNS topic instead. You could provide your own `Delivery` implementation based on the one here: https://github.com/birchill/bugsnag-zero/blob/main/src/fetch-delivery.ts

That said, it's probably not too hard to add support for custom endpoints so perhaps I should just do that!

**Comment by frixaco** [comment]
@birtles Thanks for quick response! It would be great to have custom endpoint support For now, I'll try to implementing custom `Delivery` and see if that works.

**Comment by birtles** [comment]
@frixaco I've added custom endpoint support 0.4.17. Please let me know if it works for you.

**Comment by birtles** [comment]
(Oops, looks like 0.4.17 had a bug in it so I published 0.4.18 now.)

**Comment by frixaco** [comment]
Hey @birtles . Thank you very much for such quick update!

It might take some time before I can test it, so I'll be closing this issue for now. Thanks again.
