### ISSUE TITLE
Consider adding `passive: true` to `addEventListener` breadcrumbs

### ISSUE THREAD

**Issue by xPaw** [birchill/bugsnag-zero#112]
> When set to true, options’s [passive](https://dom.spec.whatwg.org/#dom-addeventlisteneroptions-passive) indicates that the [callback](https://dom.spec.whatwg.org/#event-listener-callback) will not cancel the event by invoking [preventDefault()](https://dom.spec.whatwg.org/#dom-event-preventdefault). This is used to enable performance optimizations described in [§ 2.8 Observing event listeners](https://dom.spec.whatwg.org/#observing-event-listeners).

This is usually done for scroll/touch events, but I imagine it should be fine to set for `click` event too.

**Comment by birtles** [comment]
Yeah, I was under the impression it made no difference for `click` events but it probably doesn't hurt to add it.

**Comment by birtles** [comment]
I haven't been able to find any mention of any browser optimizing handling of any of the events we currently listen on ('click', 'pagehide', 'pageshow', 'load', 'DOMContentLoaded', 'hashchange', etc.) so I don't think it's worth adding this since adding it will increase the package size fractionally.

Initially I was going to just add it but then I realised this issue was about more than just the 'click' event. I'm closing this for now but please let me know if you disagree.
